## Amy Njenga - Lab 3
### Importing pandas

In [4]:

import pandas as pd

### Creation of the Movies Dataset

In [5]:
movies = pd.DataFrame({
    "movie_id" : [1,2,3,4,5,6,7,8,9,10],
    "title": ["Galaxy Mission","Love in Nairobi","Final Battle","Family Weekend", "Future World","Broken Hearts","City Detectives","Space Warriors", "Wedding Weekend","Hidden Truth"],
    "Action": [1,0,1,0,1,0,1,1,0,0],
    "Comedy" : [0,0,0,1,0,0,0,0,1,0],
    "Drama": [0,1,0,0,0,1,1,0,0,1],
    "Romance": [0,1,0,0,0,1,0,0,1,0],
    "SciFi": [1,0,0,0,1,0,0,1,0,0]

})
movies

   movie_id            title  Action  Comedy  Drama  Romance  SciFi
0         1   Galaxy Mission       1       0      0        0      1
1         2  Love in Nairobi       0       0      1        1      0
2         3     Final Battle       1       0      0        0      0
3         4   Family Weekend       0       1      0        0      0
4         5     Future World       1       0      0        0      1
5         6    Broken Hearts       0       0      1        1      0
6         7  City Detectives       1       0      1        0      0
7         8   Space Warriors       1       0      0        0      1
8         9  Wedding Weekend       0       1      0        1      0
9        10     Hidden Truth       0       0      1        0      0

### Inspecting the Dataset

In [6]:
movies.head()
movies.shape
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  10 non-null     int64
 1   title     10 non-null     str
 2   Action    10 non-null     int64
 3   Comedy    10 non-null     int64
 4   Drama     10 non-null     int64
 5   Romance   10 non-null     int64
 6   SciFi     10 non-null     int64
dtypes: int64(6), str(1)
memory usage: 692.0 bytes

### Questions:
1. How many movies are in the dataset?- 10

2. How many genre features exist?- 5

3. What does one row represent?- One movie, its id, title, and genre classification

### Separation of Movie Features

In [7]:
features = ["Action", "Comedy", "Drama", "Romance", "SciFi"] 
movie_features = movies[features] 
movie_features

   Action  Comedy  Drama  Romance  SciFi
0       1       0      0        0      1
1       0       0      1        1      0
2       1       0      0        0      0
3       0       1      0        0      0
4       1       0      0        0      1
5       0       0      1        1      0
6       1       0      1        0      0
7       1       0      0        0      1
8       0       1      0        1      0
9       0       0      1        0      0

### Inspecting a single item profile

In [8]:
movies.loc[
    movies["title"] == "Galaxy Mission"
]

   movie_id           title  Action  Comedy  Drama  Romance  SciFi
0         1  Galaxy Mission       1       0      0        0      1

## Explanation for 1s and 0s

The 1s and 0s represent true or false so whether a movies fits into a specific category, in this case, the features. So "Glaxy Mission" is and Action movie as well as a SciFi movie. It does not fit into the drama, comedy or romance genres

### Creation of User Ratings

In [9]:
ratings = pd.DataFrame({ "movie_id": [1, 2, 3, 5], "rating": [5, 2, 4, 5] }) 
ratings

   movie_id  rating
0         1       5
1         2       2
2         3       4
3         5       5

### Joining Ratings iwth Movie Features

In [10]:
user_movies = ratings.merge( movies, on="movie_id" ) 
user_movies

   movie_id  rating            title  Action  Comedy  Drama  Romance  SciFi
0         1       5   Galaxy Mission       1       0      0        0      1
1         2       2  Love in Nairobi       0       0      1        1      0
2         3       4     Final Battle       1       0      0        0      0
3         5       5     Future World       1       0      0        0      1

### Examine the User's History

In [11]:
user_movies[ ["title", "rating", "Action", "Comedy", "Drama", "Romance", "SciFi"] ]

             title  rating  Action  Comedy  Drama  Romance  SciFi
0   Galaxy Mission       5       1       0      0        0      1
1  Love in Nairobi       2       0       0      1        1      0
2     Final Battle       4       1       0      0        0      0
3     Future World       5       1       0      0        0      1

### Observed user preference

This user seems to prefer Action-SciFi movies over Romace, Comedy and Drama movies

### Select Rated Features

In [16]:
rated_features = user_movies[features] 
user_ratings = user_movies["rating"] 
rated_features 
user_ratings

0    5
1    2
2    4
3    5
Name: rating, dtype: int64

### Weight Features using Ratings

In [17]:
weighted_features = rated_features.mul( user_ratings, axis=0
) 
weighted_features

   Action  Comedy  Drama  Romance  SciFi
0       5       0      0        0      5
1       0       0      2        2      0
2       4       0      0        0      0
3       5       0      0        0      5

### Building the User Profile

In [18]:
user_profile = weighted_features.sum() 
user_profile

Action     14
Comedy      0
Drama       2
Romance     2
SciFi      10
dtype: int64

### Interpretation of the User Profile

In [19]:
user_profile.sort_values( ascending=False )

Action     14
SciFi      10
Drama       2
Romance     2
Comedy      0
dtype: int64

The top two genres for this user are Action and SciFi with scores of 14 and 10 respectively. This suggests that the user enjoys those types of movies more because they were rated higher.

### Normalise the User Profile

In [20]:
user_profile_normalized = ( user_profile / user_profile.sum() ) 
user_profile_normalized

Action     0.500000
Comedy     0.000000
Drama      0.071429
Romance    0.071429
SciFi      0.357143
dtype: float64

### Scoring every movie

In [21]:
movies["recommendation_score"] = ( movie_features .mul(user_profile_normalized) .sum(axis=1) ) 
movies[["title", "recommendation_score"]]

             title  recommendation_score
0   Galaxy Mission              0.857143
1  Love in Nairobi              0.142857
2     Final Battle              0.500000
3   Family Weekend              0.000000
4     Future World              0.857143
5    Broken Hearts              0.142857
6  City Detectives              0.571429
7   Space Warriors              0.857143
8  Wedding Weekend              0.071429
9     Hidden Truth              0.071429

### Ranking of Movies

In [22]:
ranked_movies = movies.sort_values( "recommendation_score", ascending=False ) 
ranked_movies[["title", "recommendation_score"]]

             title  recommendation_score
0   Galaxy Mission              0.857143
4     Future World              0.857143
7   Space Warriors              0.857143
6  City Detectives              0.571429
2     Final Battle              0.500000
1  Love in Nairobi              0.142857
5    Broken Hearts              0.142857
8  Wedding Weekend              0.071429
9     Hidden Truth              0.071429
3   Family Weekend              0.000000

### Removal of watched Movies

In [23]:
watched_movies = ratings["movie_id"] 
recommendations = ranked_movies[ ~ranked_movies["movie_id"].isin(watched_movies) ] 
recommendations[["title", "recommendation_score"]]

             title  recommendation_score
7   Space Warriors              0.857143
6  City Detectives              0.571429
5    Broken Hearts              0.142857
8  Wedding Weekend              0.071429
9     Hidden Truth              0.071429
3   Family Weekend              0.000000

### Top 3 Recommendations

In [24]:
top_3 = recommendations[ ["title", "recommendation_score"] ].head(3) 
top_3

             title  recommendation_score
7   Space Warriors              0.857143
6  City Detectives              0.571429
5    Broken Hearts              0.142857

The top 3 recommendations, firstly are all new movies to the user. They are Space Warriors, City Detectives and Broken Hearts all of which contain some of the users preferred features such as Action, SciFi and a bit of Drama

### Building of a Reusable Function

In [36]:
def recommend_movies(ratings, movies, features, n=3):
    user_movies = ratings.merge(movies, on="movie_id")
    rated_features = user_movies[features]
    weighted_features = rated_features.mul(user_movies["rating"], axis=0)

    user_profile = weighted_features.sum()
    user_profile = user_profile / user_profile.sum()

    results = movies.copy()
    results["recommendation_score"] = (
        results[features].mul(user_profile).sum(axis=1)
    )

    watched = ratings["movie_id"]
    results = results.loc[~results["movie_id"].isin(watched)]

    return results.sort_values(
        "recommendation_score", ascending=False
    ).head(n)


recommend_movies(ratings, movies, features)

,movie_id,title,Action,Comedy,Drama,Romance,SciFi,recommendation_score
7,8,Space Warriors,1,0,0,0,1,0.857143
6,7,City Detectives,1,0,1,0,0,0.571429
5,6,Broken Hearts,0,0,1,1,0,0.142857

### Test on a different user

In [39]:
user_b_ratings = pd.DataFrame({ "movie_id": [2, 4, 6, 9], "rating": [5, 4, 5, 4] }) 
recommend_movies( user_b_ratings,movies, features )

,movie_id,title,Action,Comedy,Drama,Romance,SciFi,recommendation_score
9,10,Hidden Truth,0,0,1,0,0,0.3125
6,7,City Detectives,1,0,1,0,0,0.3125
2,3,Final Battle,1,0,0,0,0,0.0000

User A received more Action and SciFi recommendations while User B received more Action + Drama combinations, this is probably because Use B rated Drama movies highly, influencing their preference profile

Suppose User C has watched only Galaxy Mission and rated it 5 stars.

4. What will the model learn about User C?- The model will learn that the user prefers Action + SciFi Movies

5. Which genres will dominate the profile? - From the answer above, this means that Action and SciFi genres will dominate the profile

6. What could go wrong with the recommendations?- The recommendations may lean too heavily on those genres even though they may not fully represent the user's taste, it is only based on the limited ratings

7. Is one rating enough to understand a user's preferences?- No, one rating is not enough to undertsnad a user's preference

### Adding my own movie

In [40]:
new_movie = { "movie_id": 11, "title": "The Invite", "Action": 0, "Comedy": 1, "Drama": 1, "Romance": 10, "SciFi": 0 } 
movies = pd.concat( [movies, pd.DataFrame([new_movie])], ignore_index=True )

### Adding my own user

In [42]:
my_user = pd.DataFrame({ "movie_id": [1, 3, 6, 11], "rating": [5, 5, 2, 1] }) 
recommend_movies( my_user, movies, features, n=5 )

,movie_id,title,Action,Comedy,Drama,Romance,SciFi,recommendation_score
1,2,Love in Nairobi,0,0,1,1,0,0.483871
4,5,Future World,1,0,0,0,1,0.483871
7,8,Space Warriors,1,0,0,0,1,0.483871
8,9,Wedding Weekend,0,1,0,1,0,0.419355
6,7,City Detectives,1,0,1,0,0,0.419355

8. What are your user's two strongest preferences? - the top 2 preferences are romance and action

9. Which three movies received the highest recommendation scores?- The top 3 scores were from Love in Nairobi, Future World and Space Warriors

10. Why did the top movie rank first?- The top movie ranked first because it has the highest proportion of the score, with Drama and Romance features

11. Did any recommendation surprise you?- The wedding weeknd surprised me because it is a comedy and comedy isnt a strong feature in this user's profile

12. What important information is the model ignoring?- The model is ignoring films of other genres

### Limitations

1. A large amount of film information is ignored such as actors, directors, release year, langauge etc. all of which could influence a user's preference profile

2. The model relies too heavily on ratings as the only indicator of enjoyment so the resulting recommemdations may become too similar to previous liked items resulting in boredom

3. New users with little or no preference history may pose a challenge as the model has no basis onto which it can build a preference profile, this is similar to the cold-start problem

### Final Question

If two users have watched exactly the same movies but gave them different ratings, should this recommender produce the same recommendations for both users? Use your Week 3 model to explain your answer.

The answer is no. The recommender should not produce the same recommendations, this is because the ratings should inform the preference profile. This would take into account the genres which have been rated highly thus giving both users a different list of recommendations